/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarRouteRouteImport } from './routes/car/route'
import { Route as ChampionshipRouteRouteImport } from './routes/championship/route'
import { Route as HqRouteRouteImport } from './routes/hq/route'
import { Route as MediaRouteRouteImport } from './routes/media/route'
import { Route as MoneyRouteRouteImport } from './routes/money/route'
import { Route as PeopleRouteRouteImport } from './routes/people/route'
import { Route as TeamRouteRouteImport } from './routes/team/route'
import { Route as WeekendRouteRouteImport } from './routes/weekend/route'
import { Route as CarIndexRouteImport } from './routes/car/index'
import { Route as CarDevelopmentRouteImport } from './routes/car/development'
import { Route as CarPhilosophyRouteImport } from './routes/car/philosophy'
import { Route as CarReliabilityRouteImport } from './routes/car/reliability'
import { Route as CarSpecsRouteImport } from './routes/car/specs'
import { Route as CarUpgradesRouteImport } from './routes/car/upgrades'
import { Route as ChampionshipIndexRouteImport } from './routes/championship/index'
import { Route as ChampionshipCalendarRouteImport } from './routes/championship/calendar'
import { Route as ChampionshipHistoryRouteImport } from './routes/championship/history'
import { Route as ChampionshipRegulationsRouteImport } from './routes/championship/regulations'
import { Route as ChampionshipRivalsRouteImport } from './routes/championship/rivals'
import { Route as ChampionshipStandingsRouteImport } from './routes/championship/standings'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as DevRaceRouteImport } from './routes/dev/race'
import { Route as HqIndexRouteImport } from './routes/hq/index'
import { Route as HqOverviewRouteImport } from './routes/hq/overview'
import { Route as MediaIndexRouteImport } from './routes/media/index'
import { Route as MediaCrisesRouteImport } from './routes/media/crises'
import { Route as MediaPressRouteImport } from './routes/media/press'
import { Route as MediaReputationRouteImport } from './routes/media/reputation'
import { Route as MediaSocialRouteImport } from './routes/media/social'
import { Route as MoneyIndexRouteImport } from './routes/money/index'
import { Route as MoneyBudgetRouteImport } from './routes/money/budget'
import { Route as MoneyCostCapRouteImport } from './routes/money/cost-cap'
import { Route as MoneyForecastRouteImport } from './routes/money/forecast'
import { Route as MoneySponsorsRouteImport } from './routes/money/sponsors'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PeopleAcademyRouteImport } from './routes/people/academy'
import { Route as PeopleContractsRouteImport } from './routes/people/contracts'
import { Route as PeopleDriversRouteImport } from './routes/people/drivers'
import { Route as PeopleMarketRouteImport } from './routes/people/market'
import { Route as PeopleStaffRouteImport } from './routes/people/staff'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as TeamDepartmentsRouteImport } from './routes/team/departments'
import { Route as TeamInfrastructureRouteImport } from './routes/team/infrastructure'
import { Route as TeamMoraleRouteImport } from './routes/team/morale'
import { Route as WeekendIndexRouteImport } from './routes/weekend/index'
import { Route as WeekendProgrammesRouteImport } from './routes/weekend/programmes'
import { Route as WeekendRaceRouteImport } from './routes/weekend/race'
import { Route as WeekendScheduleRouteImport } from './routes/weekend/schedule'
import { Route as WeekendSetupRouteImport } from './routes/weekend/setup'
import { Route as WeekendStrategyRouteImport } from './routes/weekend/strategy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRouteRoute = CarRouteRouteImport.update({
  id: '/car',
  path: '/car',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipRouteRoute = ChampionshipRouteRouteImport.update({
  id: '/championship',
  path: '/championship',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRouteRoute = HqRouteRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRouteRoute = MediaRouteRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRouteRoute = MoneyRouteRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRouteRoute = PeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRouteRoute = TeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekendRouteRoute = WeekendRouteRouteImport.update({
  id: '/weekend',
  path: '/weekend',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIndexRoute = CarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarDevelopmentRoute = CarDevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarPhilosophyRoute = CarPhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarReliabilityRoute = CarReliabilityRouteImport.update({
  id: '/reliability',
  path: '/reliability',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarSpecsRoute = CarSpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => CarRouteRoute,
} as any)
const CarUpgradesRoute = CarUpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => CarRouteRoute,
} as any)
const ChampionshipIndexRoute = ChampionshipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChampionshipRouteRoute,
} as any)
const ChampionshipCalendarRoute = ChampionshipCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ChampionshipRouteRoute,
} as any)
const ChampionshipHistoryRoute = ChampionshipHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ChampionshipRouteRoute,
} as any)
const ChampionshipRegulationsRoute = ChampionshipRegulationsRouteImport.update({
  id: '/regulations',
  path: '/regulations',
  getParentRoute: () => ChampionshipRouteRoute,
} as any)
const ChampionshipRivalsRoute = ChampionshipRivalsRouteImport.update({
  id: '/rivals',
  path: '/rivals',
  getParentRoute: () => ChampionshipRouteRoute,
} as any)
const ChampionshipStandingsRoute = ChampionshipStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => ChampionshipRouteRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRaceRoute = DevRaceRouteImport.update({
  id: '/dev/race',
  path: '/dev/race',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIndexRoute = HqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqRouteRoute,
} as any)
const HqOverviewRoute = HqOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => HqRouteRoute,
} as any)
const MediaIndexRoute = MediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MediaRouteRoute,
} as any)
const MediaCrisesRoute = MediaCrisesRouteImport.update({
  id: '/crises',
  path: '/crises',
  getParentRoute: () => MediaRouteRoute,
} as any)
const MediaPressRoute = MediaPressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => MediaRouteRoute,
} as any)
const MediaReputationRoute = MediaReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => MediaRouteRoute,
} as any)
const MediaSocialRoute = MediaSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => MediaRouteRoute,
} as any)
const MoneyIndexRoute = MoneyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoneyRouteRoute,
} as any)
const MoneyBudgetRoute = MoneyBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => MoneyRouteRoute,
} as any)
const MoneyCostCapRoute = MoneyCostCapRouteImport.update({
  id: '/cost-cap',
  path: '/cost-cap',
  getParentRoute: () => MoneyRouteRoute,
} as any)
const MoneyForecastRoute = MoneyForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => MoneyRouteRoute,
} as any)
const MoneySponsorsRoute = MoneySponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => MoneyRouteRoute,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleAcademyRoute = PeopleAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleContractsRoute = PeopleContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleDriversRoute = PeopleDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleMarketRoute = PeopleMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const PeopleStaffRoute = PeopleStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PeopleRouteRoute,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamDepartmentsRoute = TeamDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamInfrastructureRoute = TeamInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => TeamRouteRoute,
} as any)
const TeamMoraleRoute = TeamMoraleRouteImport.update({
  id: '/morale',
  path: '/morale',
  getParentRoute: () => TeamRouteRoute,
} as any)
const WeekendIndexRoute = WeekendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeekendRouteRoute,
} as any)
const WeekendProgrammesRoute = WeekendProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => WeekendRouteRoute,
} as any)
const WeekendRaceRoute = WeekendRaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => WeekendRouteRoute,
} as any)
const WeekendScheduleRoute = WeekendScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => WeekendRouteRoute,
} as any)
const WeekendSetupRoute = WeekendSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => WeekendRouteRoute,
} as any)
const WeekendStrategyRoute = WeekendStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => WeekendRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/car': typeof CarRouteRouteWithChildren
  '/championship': typeof ChampionshipRouteRouteWithChildren
  '/hq': typeof HqRouteRouteWithChildren
  '/media': typeof MediaRouteRouteWithChildren
  '/money': typeof MoneyRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/weekend': typeof WeekendRouteRouteWithChildren
  '/car/development': typeof CarDevelopmentRoute
  '/car/philosophy': typeof CarPhilosophyRoute
  '/car/reliability': typeof CarReliabilityRoute
  '/car/specs': typeof CarSpecsRoute
  '/car/upgrades': typeof CarUpgradesRoute
  '/championship/calendar': typeof ChampionshipCalendarRoute
  '/championship/history': typeof ChampionshipHistoryRoute
  '/championship/regulations': typeof ChampionshipRegulationsRoute
  '/championship/rivals': typeof ChampionshipRivalsRoute
  '/championship/standings': typeof ChampionshipStandingsRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/race': typeof DevRaceRoute
  '/hq/overview': typeof HqOverviewRoute
  '/media/crises': typeof MediaCrisesRoute
  '/media/press': typeof MediaPressRoute
  '/media/reputation': typeof MediaReputationRoute
  '/media/social': typeof MediaSocialRoute
  '/money/budget': typeof MoneyBudgetRoute
  '/money/cost-cap': typeof MoneyCostCapRoute
  '/money/forecast': typeof MoneyForecastRoute
  '/money/sponsors': typeof MoneySponsorsRoute
  '/people/academy': typeof PeopleAcademyRoute
  '/people/contracts': typeof PeopleContractsRoute
  '/people/drivers': typeof PeopleDriversRoute
  '/people/market': typeof PeopleMarketRoute
  '/people/staff': typeof PeopleStaffRoute
  '/team/departments': typeof TeamDepartmentsRoute
  '/team/infrastructure': typeof TeamInfrastructureRoute
  '/team/morale': typeof TeamMoraleRoute
  '/weekend/programmes': typeof WeekendProgrammesRoute
  '/weekend/race': typeof WeekendRaceRoute
  '/weekend/schedule': typeof WeekendScheduleRoute
  '/weekend/setup': typeof WeekendSetupRoute
  '/weekend/strategy': typeof WeekendStrategyRoute
  '/car/': typeof CarIndexRoute
  '/championship/': typeof ChampionshipIndexRoute
  '/hq/': typeof HqIndexRoute
  '/media/': typeof MediaIndexRoute
  '/money/': typeof MoneyIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/team/': typeof TeamIndexRoute
  '/weekend/': typeof WeekendIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/car/development': typeof CarDevelopmentRoute
  '/car/philosophy': typeof CarPhilosophyRoute
  '/car/reliability': typeof CarReliabilityRoute
  '/car/specs': typeof CarSpecsRoute
  '/car/upgrades': typeof CarUpgradesRoute
  '/championship/calendar': typeof ChampionshipCalendarRoute
  '/championship/history': typeof ChampionshipHistoryRoute
  '/championship/regulations': typeof ChampionshipRegulationsRoute
  '/championship/rivals': typeof ChampionshipRivalsRoute
  '/championship/standings': typeof ChampionshipStandingsRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/race': typeof DevRaceRoute
  '/hq/overview': typeof HqOverviewRoute
  '/media/crises': typeof MediaCrisesRoute
  '/media/press': typeof MediaPressRoute
  '/media/reputation': typeof MediaReputationRoute
  '/media/social': typeof MediaSocialRoute
  '/money/budget': typeof MoneyBudgetRoute
  '/money/cost-cap': typeof MoneyCostCapRoute
  '/money/forecast': typeof MoneyForecastRoute
  '/money/sponsors': typeof MoneySponsorsRoute
  '/people/academy': typeof PeopleAcademyRoute
  '/people/contracts': typeof PeopleContractsRoute
  '/people/drivers': typeof PeopleDriversRoute
  '/people/market': typeof PeopleMarketRoute
  '/people/staff': typeof PeopleStaffRoute
  '/team/departments': typeof TeamDepartmentsRoute
  '/team/infrastructure': typeof TeamInfrastructureRoute
  '/team/morale': typeof TeamMoraleRoute
  '/weekend/programmes': typeof WeekendProgrammesRoute
  '/weekend/race': typeof WeekendRaceRoute
  '/weekend/schedule': typeof WeekendScheduleRoute
  '/weekend/setup': typeof WeekendSetupRoute
  '/weekend/strategy': typeof WeekendStrategyRoute
  '/car': typeof CarIndexRoute
  '/championship': typeof ChampionshipIndexRoute
  '/hq': typeof HqIndexRoute
  '/media': typeof MediaIndexRoute
  '/money': typeof MoneyIndexRoute
  '/people': typeof PeopleIndexRoute
  '/team': typeof TeamIndexRoute
  '/weekend': typeof WeekendIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/car': typeof CarRouteRouteWithChildren
  '/championship': typeof ChampionshipRouteRouteWithChildren
  '/hq': typeof HqRouteRouteWithChildren
  '/media': typeof MediaRouteRouteWithChildren
  '/money': typeof MoneyRouteRouteWithChildren
  '/people': typeof PeopleRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/weekend': typeof WeekendRouteRouteWithChildren
  '/car/development': typeof CarDevelopmentRoute
  '/car/philosophy': typeof CarPhilosophyRoute
  '/car/reliability': typeof CarReliabilityRoute
  '/car/specs': typeof CarSpecsRoute
  '/car/upgrades': typeof CarUpgradesRoute
  '/championship/calendar': typeof ChampionshipCalendarRoute
  '/championship/history': typeof ChampionshipHistoryRoute
  '/championship/regulations': typeof ChampionshipRegulationsRoute
  '/championship/rivals': typeof ChampionshipRivalsRoute
  '/championship/standings': typeof ChampionshipStandingsRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/race': typeof DevRaceRoute
  '/hq/overview': typeof HqOverviewRoute
  '/media/crises': typeof MediaCrisesRoute
  '/media/press': typeof MediaPressRoute
  '/media/reputation': typeof MediaReputationRoute
  '/media/social': typeof MediaSocialRoute
  '/money/budget': typeof MoneyBudgetRoute
  '/money/cost-cap': typeof MoneyCostCapRoute
  '/money/forecast': typeof MoneyForecastRoute
  '/money/sponsors': typeof MoneySponsorsRoute
  '/people/academy': typeof PeopleAcademyRoute
  '/people/contracts': typeof PeopleContractsRoute
  '/people/drivers': typeof PeopleDriversRoute
  '/people/market': typeof PeopleMarketRoute
  '/people/staff': typeof PeopleStaffRoute
  '/team/departments': typeof TeamDepartmentsRoute
  '/team/infrastructure': typeof TeamInfrastructureRoute
  '/team/morale': typeof TeamMoraleRoute
  '/weekend/programmes': typeof WeekendProgrammesRoute
  '/weekend/race': typeof WeekendRaceRoute
  '/weekend/schedule': typeof WeekendScheduleRoute
  '/weekend/setup': typeof WeekendSetupRoute
  '/weekend/strategy': typeof WeekendStrategyRoute
  '/car/': typeof CarIndexRoute
  '/championship/': typeof ChampionshipIndexRoute
  '/hq/': typeof HqIndexRoute
  '/media/': typeof MediaIndexRoute
  '/money/': typeof MoneyIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/team/': typeof TeamIndexRoute
  '/weekend/': typeof WeekendIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/car'
    | '/championship'
    | '/hq'
    | '/media'
    | '/money'
    | '/people'
    | '/team'
    | '/weekend'
    | '/car/development'
    | '/car/philosophy'
    | '/car/reliability'
    | '/car/specs'
    | '/car/upgrades'
    | '/championship/calendar'
    | '/championship/history'
    | '/championship/regulations'
    | '/championship/rivals'
    | '/championship/standings'
    | '/dev/components'
    | '/dev/race'
    | '/hq/overview'
    | '/media/crises'
    | '/media/press'
    | '/media/reputation'
    | '/media/social'
    | '/money/budget'
    | '/money/cost-cap'
    | '/money/forecast'
    | '/money/sponsors'
    | '/people/academy'
    | '/people/contracts'
    | '/people/drivers'
    | '/people/market'
    | '/people/staff'
    | '/team/departments'
    | '/team/infrastructure'
    | '/team/morale'
    | '/weekend/programmes'
    | '/weekend/race'
    | '/weekend/schedule'
    | '/weekend/setup'
    | '/weekend/strategy'
    | '/car/'
    | '/championship/'
    | '/hq/'
    | '/media/'
    | '/money/'
    | '/people/'
    | '/team/'
    | '/weekend/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/car/development'
    | '/car/philosophy'
    | '/car/reliability'
    | '/car/specs'
    | '/car/upgrades'
    | '/championship/calendar'
    | '/championship/history'
    | '/championship/regulations'
    | '/championship/rivals'
    | '/championship/standings'
    | '/dev/components'
    | '/dev/race'
    | '/hq/overview'
    | '/media/crises'
    | '/media/press'
    | '/media/reputation'
    | '/media/social'
    | '/money/budget'
    | '/money/cost-cap'
    | '/money/forecast'
    | '/money/sponsors'
    | '/people/academy'
    | '/people/contracts'
    | '/people/drivers'
    | '/people/market'
    | '/people/staff'
    | '/team/departments'
    | '/team/infrastructure'
    | '/team/morale'
    | '/weekend/programmes'
    | '/weekend/race'
    | '/weekend/schedule'
    | '/weekend/setup'
    | '/weekend/strategy'
    | '/car'
    | '/championship'
    | '/hq'
    | '/media'
    | '/money'
    | '/people'
    | '/team'
    | '/weekend'
  id:
    | '__root__'
    | '/'
    | '/car'
    | '/championship'
    | '/hq'
    | '/media'
    | '/money'
    | '/people'
    | '/team'
    | '/weekend'
    | '/car/development'
    | '/car/philosophy'
    | '/car/reliability'
    | '/car/specs'
    | '/car/upgrades'
    | '/championship/calendar'
    | '/championship/history'
    | '/championship/regulations'
    | '/championship/rivals'
    | '/championship/standings'
    | '/dev/components'
    | '/dev/race'
    | '/hq/overview'
    | '/media/crises'
    | '/media/press'
    | '/media/reputation'
    | '/media/social'
    | '/money/budget'
    | '/money/cost-cap'
    | '/money/forecast'
    | '/money/sponsors'
    | '/people/academy'
    | '/people/contracts'
    | '/people/drivers'
    | '/people/market'
    | '/people/staff'
    | '/team/departments'
    | '/team/infrastructure'
    | '/team/morale'
    | '/weekend/programmes'
    | '/weekend/race'
    | '/weekend/schedule'
    | '/weekend/setup'
    | '/weekend/strategy'
    | '/car/'
    | '/championship/'
    | '/hq/'
    | '/media/'
    | '/money/'
    | '/people/'
    | '/team/'
    | '/weekend/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarRouteRoute: typeof CarRouteRouteWithChildren
  ChampionshipRouteRoute: typeof ChampionshipRouteRouteWithChildren
  HqRouteRoute: typeof HqRouteRouteWithChildren
  MediaRouteRoute: typeof MediaRouteRouteWithChildren
  MoneyRouteRoute: typeof MoneyRouteRouteWithChildren
  PeopleRouteRoute: typeof PeopleRouteRouteWithChildren
  TeamRouteRoute: typeof TeamRouteRouteWithChildren
  WeekendRouteRoute: typeof WeekendRouteRouteWithChildren
  DevComponentsRoute: typeof DevComponentsRoute
  DevRaceRoute: typeof DevRaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car': {
      id: '/car'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/championship': {
      id: '/championship'
      path: '/championship'
      fullPath: '/championship'
      preLoaderRoute: typeof ChampionshipRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekend': {
      id: '/weekend'
      path: '/weekend'
      fullPath: '/weekend'
      preLoaderRoute: typeof WeekendRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/': {
      id: '/car/'
      path: '/'
      fullPath: '/car/'
      preLoaderRoute: typeof CarIndexRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/development': {
      id: '/car/development'
      path: '/development'
      fullPath: '/car/development'
      preLoaderRoute: typeof CarDevelopmentRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/philosophy': {
      id: '/car/philosophy'
      path: '/philosophy'
      fullPath: '/car/philosophy'
      preLoaderRoute: typeof CarPhilosophyRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/reliability': {
      id: '/car/reliability'
      path: '/reliability'
      fullPath: '/car/reliability'
      preLoaderRoute: typeof CarReliabilityRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/specs': {
      id: '/car/specs'
      path: '/specs'
      fullPath: '/car/specs'
      preLoaderRoute: typeof CarSpecsRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/car/upgrades': {
      id: '/car/upgrades'
      path: '/upgrades'
      fullPath: '/car/upgrades'
      preLoaderRoute: typeof CarUpgradesRouteImport
      parentRoute: typeof CarRouteRoute
    }
    '/championship/': {
      id: '/championship/'
      path: '/'
      fullPath: '/championship/'
      preLoaderRoute: typeof ChampionshipIndexRouteImport
      parentRoute: typeof ChampionshipRouteRoute
    }
    '/championship/calendar': {
      id: '/championship/calendar'
      path: '/calendar'
      fullPath: '/championship/calendar'
      preLoaderRoute: typeof ChampionshipCalendarRouteImport
      parentRoute: typeof ChampionshipRouteRoute
    }
    '/championship/history': {
      id: '/championship/history'
      path: '/history'
      fullPath: '/championship/history'
      preLoaderRoute: typeof ChampionshipHistoryRouteImport
      parentRoute: typeof ChampionshipRouteRoute
    }
    '/championship/regulations': {
      id: '/championship/regulations'
      path: '/regulations'
      fullPath: '/championship/regulations'
      preLoaderRoute: typeof ChampionshipRegulationsRouteImport
      parentRoute: typeof ChampionshipRouteRoute
    }
    '/championship/rivals': {
      id: '/championship/rivals'
      path: '/rivals'
      fullPath: '/championship/rivals'
      preLoaderRoute: typeof ChampionshipRivalsRouteImport
      parentRoute: typeof ChampionshipRouteRoute
    }
    '/championship/standings': {
      id: '/championship/standings'
      path: '/standings'
      fullPath: '/championship/standings'
      preLoaderRoute: typeof ChampionshipStandingsRouteImport
      parentRoute: typeof ChampionshipRouteRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/race': {
      id: '/dev/race'
      path: '/dev/race'
      fullPath: '/dev/race'
      preLoaderRoute: typeof DevRaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/': {
      id: '/hq/'
      path: '/'
      fullPath: '/hq/'
      preLoaderRoute: typeof HqIndexRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/hq/overview': {
      id: '/hq/overview'
      path: '/overview'
      fullPath: '/hq/overview'
      preLoaderRoute: typeof HqOverviewRouteImport
      parentRoute: typeof HqRouteRoute
    }
    '/media/': {
      id: '/media/'
      path: '/'
      fullPath: '/media/'
      preLoaderRoute: typeof MediaIndexRouteImport
      parentRoute: typeof MediaRouteRoute
    }
    '/media/crises': {
      id: '/media/crises'
      path: '/crises'
      fullPath: '/media/crises'
      preLoaderRoute: typeof MediaCrisesRouteImport
      parentRoute: typeof MediaRouteRoute
    }
    '/media/press': {
      id: '/media/press'
      path: '/press'
      fullPath: '/media/press'
      preLoaderRoute: typeof MediaPressRouteImport
      parentRoute: typeof MediaRouteRoute
    }
    '/media/reputation': {
      id: '/media/reputation'
      path: '/reputation'
      fullPath: '/media/reputation'
      preLoaderRoute: typeof MediaReputationRouteImport
      parentRoute: typeof MediaRouteRoute
    }
    '/media/social': {
      id: '/media/social'
      path: '/social'
      fullPath: '/media/social'
      preLoaderRoute: typeof MediaSocialRouteImport
      parentRoute: typeof MediaRouteRoute
    }
    '/money/': {
      id: '/money/'
      path: '/'
      fullPath: '/money/'
      preLoaderRoute: typeof MoneyIndexRouteImport
      parentRoute: typeof MoneyRouteRoute
    }
    '/money/budget': {
      id: '/money/budget'
      path: '/budget'
      fullPath: '/money/budget'
      preLoaderRoute: typeof MoneyBudgetRouteImport
      parentRoute: typeof MoneyRouteRoute
    }
    '/money/cost-cap': {
      id: '/money/cost-cap'
      path: '/cost-cap'
      fullPath: '/money/cost-cap'
      preLoaderRoute: typeof MoneyCostCapRouteImport
      parentRoute: typeof MoneyRouteRoute
    }
    '/money/forecast': {
      id: '/money/forecast'
      path: '/forecast'
      fullPath: '/money/forecast'
      preLoaderRoute: typeof MoneyForecastRouteImport
      parentRoute: typeof MoneyRouteRoute
    }
    '/money/sponsors': {
      id: '/money/sponsors'
      path: '/sponsors'
      fullPath: '/money/sponsors'
      preLoaderRoute: typeof MoneySponsorsRouteImport
      parentRoute: typeof MoneyRouteRoute
    }
    '/people/': {
      id: '/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/people/academy': {
      id: '/people/academy'
      path: '/academy'
      fullPath: '/people/academy'
      preLoaderRoute: typeof PeopleAcademyRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/people/contracts': {
      id: '/people/contracts'
      path: '/contracts'
      fullPath: '/people/contracts'
      preLoaderRoute: typeof PeopleContractsRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/people/drivers': {
      id: '/people/drivers'
      path: '/drivers'
      fullPath: '/people/drivers'
      preLoaderRoute: typeof PeopleDriversRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/people/market': {
      id: '/people/market'
      path: '/market'
      fullPath: '/people/market'
      preLoaderRoute: typeof PeopleMarketRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/people/staff': {
      id: '/people/staff'
      path: '/staff'
      fullPath: '/people/staff'
      preLoaderRoute: typeof PeopleStaffRouteImport
      parentRoute: typeof PeopleRouteRoute
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/departments': {
      id: '/team/departments'
      path: '/departments'
      fullPath: '/team/departments'
      preLoaderRoute: typeof TeamDepartmentsRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/infrastructure': {
      id: '/team/infrastructure'
      path: '/infrastructure'
      fullPath: '/team/infrastructure'
      preLoaderRoute: typeof TeamInfrastructureRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/team/morale': {
      id: '/team/morale'
      path: '/morale'
      fullPath: '/team/morale'
      preLoaderRoute: typeof TeamMoraleRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/weekend/': {
      id: '/weekend/'
      path: '/'
      fullPath: '/weekend/'
      preLoaderRoute: typeof WeekendIndexRouteImport
      parentRoute: typeof WeekendRouteRoute
    }
    '/weekend/programmes': {
      id: '/weekend/programmes'
      path: '/programmes'
      fullPath: '/weekend/programmes'
      preLoaderRoute: typeof WeekendProgrammesRouteImport
      parentRoute: typeof WeekendRouteRoute
    }
    '/weekend/race': {
      id: '/weekend/race'
      path: '/race'
      fullPath: '/weekend/race'
      preLoaderRoute: typeof WeekendRaceRouteImport
      parentRoute: typeof WeekendRouteRoute
    }
    '/weekend/schedule': {
      id: '/weekend/schedule'
      path: '/schedule'
      fullPath: '/weekend/schedule'
      preLoaderRoute: typeof WeekendScheduleRouteImport
      parentRoute: typeof WeekendRouteRoute
    }
    '/weekend/setup': {
      id: '/weekend/setup'
      path: '/setup'
      fullPath: '/weekend/setup'
      preLoaderRoute: typeof WeekendSetupRouteImport
      parentRoute: typeof WeekendRouteRoute
    }
    '/weekend/strategy': {
      id: '/weekend/strategy'
      path: '/strategy'
      fullPath: '/weekend/strategy'
      preLoaderRoute: typeof WeekendStrategyRouteImport
      parentRoute: typeof WeekendRouteRoute
    }
  }
}

interface CarRouteRouteChildren {
  CarDevelopmentRoute: typeof CarDevelopmentRoute
  CarPhilosophyRoute: typeof CarPhilosophyRoute
  CarReliabilityRoute: typeof CarReliabilityRoute
  CarSpecsRoute: typeof CarSpecsRoute
  CarUpgradesRoute: typeof CarUpgradesRoute
  CarIndexRoute: typeof CarIndexRoute
}

const CarRouteRouteChildren: CarRouteRouteChildren = {
  CarDevelopmentRoute: CarDevelopmentRoute,
  CarPhilosophyRoute: CarPhilosophyRoute,
  CarReliabilityRoute: CarReliabilityRoute,
  CarSpecsRoute: CarSpecsRoute,
  CarUpgradesRoute: CarUpgradesRoute,
  CarIndexRoute: CarIndexRoute,
}

const CarRouteRouteWithChildren = CarRouteRoute._addFileChildren(
  CarRouteRouteChildren,
)

interface ChampionshipRouteRouteChildren {
  ChampionshipCalendarRoute: typeof ChampionshipCalendarRoute
  ChampionshipHistoryRoute: typeof ChampionshipHistoryRoute
  ChampionshipRegulationsRoute: typeof ChampionshipRegulationsRoute
  ChampionshipRivalsRoute: typeof ChampionshipRivalsRoute
  ChampionshipStandingsRoute: typeof ChampionshipStandingsRoute
  ChampionshipIndexRoute: typeof ChampionshipIndexRoute
}

const ChampionshipRouteRouteChildren: ChampionshipRouteRouteChildren = {
  ChampionshipCalendarRoute: ChampionshipCalendarRoute,
  ChampionshipHistoryRoute: ChampionshipHistoryRoute,
  ChampionshipRegulationsRoute: ChampionshipRegulationsRoute,
  ChampionshipRivalsRoute: ChampionshipRivalsRoute,
  ChampionshipStandingsRoute: ChampionshipStandingsRoute,
  ChampionshipIndexRoute: ChampionshipIndexRoute,
}

const ChampionshipRouteRouteWithChildren =
  ChampionshipRouteRoute._addFileChildren(ChampionshipRouteRouteChildren)

interface HqRouteRouteChildren {
  HqOverviewRoute: typeof HqOverviewRoute
  HqIndexRoute: typeof HqIndexRoute
}

const HqRouteRouteChildren: HqRouteRouteChildren = {
  HqOverviewRoute: HqOverviewRoute,
  HqIndexRoute: HqIndexRoute,
}

const HqRouteRouteWithChildren =
  HqRouteRoute._addFileChildren(HqRouteRouteChildren)

interface MediaRouteRouteChildren {
  MediaCrisesRoute: typeof MediaCrisesRoute
  MediaPressRoute: typeof MediaPressRoute
  MediaReputationRoute: typeof MediaReputationRoute
  MediaSocialRoute: typeof MediaSocialRoute
  MediaIndexRoute: typeof MediaIndexRoute
}

const MediaRouteRouteChildren: MediaRouteRouteChildren = {
  MediaCrisesRoute: MediaCrisesRoute,
  MediaPressRoute: MediaPressRoute,
  MediaReputationRoute: MediaReputationRoute,
  MediaSocialRoute: MediaSocialRoute,
  MediaIndexRoute: MediaIndexRoute,
}

const MediaRouteRouteWithChildren = MediaRouteRoute._addFileChildren(
  MediaRouteRouteChildren,
)

interface MoneyRouteRouteChildren {
  MoneyBudgetRoute: typeof MoneyBudgetRoute
  MoneyCostCapRoute: typeof MoneyCostCapRoute
  MoneyForecastRoute: typeof MoneyForecastRoute
  MoneySponsorsRoute: typeof MoneySponsorsRoute
  MoneyIndexRoute: typeof MoneyIndexRoute
}

const MoneyRouteRouteChildren: MoneyRouteRouteChildren = {
  MoneyBudgetRoute: MoneyBudgetRoute,
  MoneyCostCapRoute: MoneyCostCapRoute,
  MoneyForecastRoute: MoneyForecastRoute,
  MoneySponsorsRoute: MoneySponsorsRoute,
  MoneyIndexRoute: MoneyIndexRoute,
}

const MoneyRouteRouteWithChildren = MoneyRouteRoute._addFileChildren(
  MoneyRouteRouteChildren,
)

interface PeopleRouteRouteChildren {
  PeopleAcademyRoute: typeof PeopleAcademyRoute
  PeopleContractsRoute: typeof PeopleContractsRoute
  PeopleDriversRoute: typeof PeopleDriversRoute
  PeopleMarketRoute: typeof PeopleMarketRoute
  PeopleStaffRoute: typeof PeopleStaffRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

const PeopleRouteRouteChildren: PeopleRouteRouteChildren = {
  PeopleAcademyRoute: PeopleAcademyRoute,
  PeopleContractsRoute: PeopleContractsRoute,
  PeopleDriversRoute: PeopleDriversRoute,
  PeopleMarketRoute: PeopleMarketRoute,
  PeopleStaffRoute: PeopleStaffRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}

const PeopleRouteRouteWithChildren = PeopleRouteRoute._addFileChildren(
  PeopleRouteRouteChildren,
)

interface TeamRouteRouteChildren {
  TeamDepartmentsRoute: typeof TeamDepartmentsRoute
  TeamInfrastructureRoute: typeof TeamInfrastructureRoute
  TeamMoraleRoute: typeof TeamMoraleRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteRouteChildren: TeamRouteRouteChildren = {
  TeamDepartmentsRoute: TeamDepartmentsRoute,
  TeamInfrastructureRoute: TeamInfrastructureRoute,
  TeamMoraleRoute: TeamMoraleRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteRouteWithChildren = TeamRouteRoute._addFileChildren(
  TeamRouteRouteChildren,
)

interface WeekendRouteRouteChildren {
  WeekendProgrammesRoute: typeof WeekendProgrammesRoute
  WeekendRaceRoute: typeof WeekendRaceRoute
  WeekendScheduleRoute: typeof WeekendScheduleRoute
  WeekendSetupRoute: typeof WeekendSetupRoute
  WeekendStrategyRoute: typeof WeekendStrategyRoute
  WeekendIndexRoute: typeof WeekendIndexRoute
}

const WeekendRouteRouteChildren: WeekendRouteRouteChildren = {
  WeekendProgrammesRoute: WeekendProgrammesRoute,
  WeekendRaceRoute: WeekendRaceRoute,
  WeekendScheduleRoute: WeekendScheduleRoute,
  WeekendSetupRoute: WeekendSetupRoute,
  WeekendStrategyRoute: WeekendStrategyRoute,
  WeekendIndexRoute: WeekendIndexRoute,
}

const WeekendRouteRouteWithChildren = WeekendRouteRoute._addFileChildren(
  WeekendRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarRouteRoute: CarRouteRouteWithChildren,
  ChampionshipRouteRoute: ChampionshipRouteRouteWithChildren,
  HqRouteRoute: HqRouteRouteWithChildren,
  MediaRouteRoute: MediaRouteRouteWithChildren,
  MoneyRouteRoute: MoneyRouteRouteWithChildren,
  PeopleRouteRoute: PeopleRouteRouteWithChildren,
  TeamRouteRoute: TeamRouteRouteWithChildren,
  WeekendRouteRoute: WeekendRouteRouteWithChildren,
  DevComponentsRoute: DevComponentsRoute,
  DevRaceRoute: DevRaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
